In [5]:
sentences = ["I ate dinner.", 
       "We had a three-course meal.", 
       "Brad came to dinner with us.",
       "He loves fish tacos.",
       "In the end, we all felt like we ate too much.",
       "We all agreed; it was a magnificent evening."]

1. sentence transformer
2. langchain hugging
3. transformer

In [8]:
%pip install sentence-transformers

  Using cached pillow-11.1.0-cp310-cp310-win_amd64.whl.metadata (9.3 kB)
  Using cached filelock-3.17.0-py3-none-any.whl.metadata (2.9 kB)
  Using cached fsspec-2025.2.0-py3-none-any.whl.metadata (11 kB)
  Using cached PyYAML-6.0.2-cp310-cp310-win_amd64.whl.metadata (2.1 kB)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
  Using cached networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
  Using cached jinja2-3.1.5-py3-none-any.whl.metadata (2.6 kB)
  Using cached MarkupSafe-3.0.2-cp310-cp310-win_amd64.whl.metadata (4.1 kB)
  Using cached charset_normalizer-3.4.1-cp310-cp310-win_amd64.whl.metadata (36 kB)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
  Using cached urllib3-2.3.0-py3-none-any.whl.metadata (6.5 kB)
  Using cached certifi-2025.1.31-py3-none-any.whl.metadata (2.5 kB)
   ---------------------------------------- 0.0/204.2 MB ? eta -:--:--
   ---------------------------------------- 1.6/204.2 MB 7.6 MB/s eta 0:00:27
    ---------------------------

In [10]:
from sentence_transformers import SentenceTransformer

In [11]:
model = SentenceTransformer('all-mpnet-base-v2')

c:\Gen_Ai\venv\lib\site-packages\huggingface_hub\file_download.py:140: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Lovekesh\.cache\huggingface\hub\models--sentence-transformers--all-mpnet-base-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


In [12]:
sentences[0]

'I ate dinner.'

In [13]:
model.encode(sentences[0])

array([-1.58598721e-02,  4.59825359e-02, -1.46349994e-02, -4.85908203e-02,
       -3.60325468e-03,  3.17664519e-02, -3.27771753e-02,  2.11894661e-02,
        1.07367113e-02,  2.50182953e-02,  1.58237237e-02,  1.24069611e-02,
        1.62089523e-02, -1.30434958e-02,  4.58446704e-02,  4.40269783e-02,
        4.57802154e-02, -4.32263454e-03,  1.87807176e-02,  5.22198109e-03,
       -1.86415669e-02, -7.11811613e-03,  3.01358812e-02,  1.70695987e-02,
       -1.53764049e-02,  3.34171802e-02, -6.55887648e-03,  1.58591475e-02,
        1.37040038e-02, -2.02766918e-02,  3.26632820e-02,  5.48365153e-03,
       -3.53351273e-02, -1.06665187e-01,  1.85711554e-06,  3.66638936e-02,
       -1.71335302e-02,  3.34468298e-02, -6.43021613e-02,  6.90796152e-02,
        2.50845570e-02,  2.89431270e-02, -8.98414850e-03, -1.84546523e-02,
        2.81152315e-02, -2.34797616e-02,  1.21612856e-02,  6.25150800e-02,
       -8.58704150e-02, -1.84621394e-03,  7.95867294e-03, -8.42522606e-02,
       -2.26103980e-02,  

In [14]:
model.encode(sentences[0]).shape

(768,)

In [15]:
!pip install langchain
!pip install langchain-community

  Using cached pydantic-2.10.6-py3-none-any.whl.metadata (30 kB)
  Using cached aiohttp-3.11.12-cp310-cp310-win_amd64.whl.metadata (8.0 kB)
  Using cached tenacity-9.0.0-py3-none-any.whl.metadata (1.2 kB)
  Using cached aiosignal-1.3.2-py2.py3-none-any.whl.metadata (3.8 kB)
  Using cached attrs-25.1.0-py3-none-any.whl.metadata (10 kB)
  Using cached frozenlist-1.5.0-cp310-cp310-win_amd64.whl.metadata (14 kB)
  Using cached multidict-6.1.0-cp310-cp310-win_amd64.whl.metadata (5.1 kB)
  Using cached propcache-0.2.1-cp310-cp310-win_amd64.whl.metadata (9.5 kB)
  Using cached yarl-1.18.3-cp310-cp310-win_amd64.whl.metadata (71 kB)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
  Using cached pydantic_core-2.27.2-cp310-cp310-win_amd64.whl.metadata (6.7 kB)
  Using cached greenlet-3.1.1-cp310-cp310-win_amd64.whl.metadata (3.9 kB)
  Using cached anyio-4.8.0-py3-none-any.whl.metadata (4.6 kB)
  Using cached htt

In [16]:
from langchain.embeddings import HuggingFaceEmbeddings

In [17]:
embedding_model_name = "sentence-transformers/all-mpnet-base-v2"

In [18]:
model_kwargs = {"device": "cpu"}
embeddings = HuggingFaceEmbeddings(model_name=embedding_model_name,model_kwargs=model_kwargs)

C:\Users\Lovekesh\AppData\Local\Temp\ipykernel_9320\2861529945.py:2: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
  embeddings = HuggingFaceEmbeddings(model_name=embedding_model_name,model_kwargs=model_kwargs)


In [19]:
embedding_vector = embeddings.embed_query(sentences[0])

In [20]:
embedding_vector

[-0.015859872102737427,
 0.04598253592848778,
 -0.014634999446570873,
 -0.04859082028269768,
 -0.0036032546777278185,
 0.03176645189523697,
 -0.032777175307273865,
 0.02118946611881256,
 0.010736711323261261,
 0.025018295273184776,
 0.0158237237483263,
 0.012406961061060429,
 0.01620895229279995,
 -0.013043495826423168,
 0.0458446703851223,
 0.04402697831392288,
 0.04578021541237831,
 -0.004322634544223547,
 0.018780717626214027,
 0.005221981089562178,
 -0.01864156685769558,
 -0.00711811613291502,
 0.030135881155729294,
 0.01706959865987301,
 -0.015376404859125614,
 0.03341718018054962,
 -0.006558876484632492,
 0.015859147533774376,
 0.013704003766179085,
 -0.020276691764593124,
 0.03266328200697899,
 0.0054836515337228775,
 -0.035335127264261246,
 -0.10666518658399582,
 1.8571155351310153e-06,
 0.03666389361023903,
 -0.017133530229330063,
 0.03344682976603508,
 -0.06430216133594513,
 0.06907961517572403,
 0.02508455701172352,
 0.028943127021193504,
 -0.008984148502349854,
 -0.01845465

In [21]:
len(embedding_vector)

768

### one more approach with tranformer huggingface libary

In [22]:
import torch
from transformers import BertTokenizer, BertModel
import random

In [23]:
from sklearn.metrics.pairwise import cosine_similarity
random_seed=42
random.seed(random_seed)
torch.manual_seed(random_seed)

In [24]:
tokenizer=BertTokenizer.from_pretrained("bert-base-uncased")

c:\Gen_Ai\venv\lib\site-packages\huggingface_hub\file_download.py:140: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Lovekesh\.cache\huggingface\hub\models--bert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


In [25]:
model=BertModel.from_pretrained("bert-base-uncased")

In [26]:
text="Love is Learning GenAi"

In [27]:
encoding=tokenizer.batch_encode_plus([text],padding=True,truncation=True,return_tensors="pt",add_special_tokens=True)

In [28]:
input_ids=encoding["input_ids"]

In [29]:
attention_mask=encoding["attention_mask"]

In [30]:
with torch.no_grad():
  outputs=model(input_ids, attention_mask=attention_mask)
  word_embeddings=outputs.last_hidden_state

In [31]:
word_embeddings

tensor([[[-0.3439, -0.0485, -0.0720,  ..., -0.1741,  0.1750,  0.2925],
         [ 0.4111, -0.1180,  0.8904,  ..., -0.3981,  0.3051, -0.4366],
         [ 0.0123, -0.1019,  0.4601,  ...,  0.3886, -0.0176,  0.2961],
         ...,
         [-1.0282, -1.1446,  0.4008,  ..., -0.1498, -0.1582, -0.0729],
         [-0.4097, -0.6527, -0.4776,  ...,  0.0867, -0.0671, -0.4743],
         [ 0.6784,  0.1252, -0.3011,  ...,  0.0134, -0.7544, -0.3561]]])

In [32]:
word_embeddings.shape

torch.Size([1, 7, 768])

In [33]:
input_ids[0]

tensor([ 101, 2293, 2003, 4083, 8991, 4886,  102])

In [34]:
decode=tokenizer.decode(input_ids[0],skip_special_tokens=True)

In [35]:
decode

'love is learning genai'